{
 "title": "Daily Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "URLs Queue Sizes (Known URLs - Downloaded URLs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "# URLs not yet downloaded" }
   ],
   "targets": [
    {
     "expr": "sum(heritrix3_crawl_job_uris_known_total - heritrix3_crawl_job_uris_downloaded_total) by (deployment)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "URL/s download rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "# URLs / second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(heritrix3_crawl_job_uris_downloaded_total[5m])) by (deployment)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Ingest HttpFS Data Out Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_bytes_out_total{backend='default_service'}[15m])",
     "legendFormat": "{{ instance }} {{ job }}"
    }
   ]
  },
  {
   "title": "Total NPLD Data on HDFS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(ukwa_files_total_bytes{collection='npld',kind='all',stream!=''})"
    }
   ]
  },
  {
   "title": "Under-replicated",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "hdfs_under_replicated_block_count{instance='ingest:9118'}"
    }
   ]
  },
  {
   "title": "HDFS % used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hdfs_used_percent{instance='ingest:9118'}"
    }
   ]
  },
  {
   "title": "Dead Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hdfs_node_count{status='dead',instance='ingest:9118'}"
    }
   ]
  },
  {
   "title": "Live Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "hdfs_node_count{status='live',instance='ingest:9118'}"
    }
   ]
  },
  {
   "title": "HTTP Access # Down",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_http_status_code!=200) OR vector(0)"
    }
   ]
  },
  {
   "title": "# Alerts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"}) OR vector(0)"
    }
   ]
  },
  {
   "title": "DB Backup",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "ukwa_task_database_backup_size_bytes"
    }
   ]
  },
  {
   "title": "Δ(DB Backup)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 13 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(ukwa_task_database_backup_size_bytes[24h])"
    }
   ]
  },
  {
   "title": "HTTP Service Status Overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "HTTP Services" }
   ],
   "targets": [
    {
     "expr": "count(probe_http_status_code == 200)",
     "legendFormat": "OK: Count of services returning 200 OK"
    },
    {
     "expr": "count(probe_http_status_code != 200) by (instance)",
     "legendFormat": "DOWN: {{ instance }}"
    }
   ]
  },
  {
   "title": "# Tasks Run v. Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(ukwa_task_status == 1)", "legendFormat": "# jobs run successfully" },
    {
     "expr": "count(ukwa_task_status == 0) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}