{
 "title": "DC 2019 Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "DC 2019 URI Rates (URIs/second)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(heritrix3_crawl_job_uris_total[5m])) by (kind)",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "Kafka Topic Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_partition_offsets) by (topic)",
     "legendFormat": "crawler status for {{ topic }}"
    },
    {
     "expr": "sum(kafka_log_logendoffset{topic!='__consumer_offsets'}) by (topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "DC 2019 URL Counts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(heritrix3_crawl_job_uris_total) by (kind)",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "DC 2019 Queue Depths",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(heritrix3_crawl_job_queue_depth) by (kind)",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "DC 2019 Bytes Rates (bytes/second)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(heritrix3_crawl_job_bytes_total[10m])) by (kind)",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "DC 2019 Queues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(heritrix3_crawl_job_queues_total) by (kind)",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "DC 2019 Crawler Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(heritrix3_crawl_job_threads_total) by (kind)",
     "legendFormat": "{{ kind }}"
    }
   ]
  }
 ]
}