{
 "title": "DC Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "URL Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(heritrix3_crawl_job_uris_total{job='npld-dc-heritrix-workers',kind!~'queued|finished'}[30m])) by (kind)",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"crawler08:9100\", mountpoint=\"/opt\"}",
     "legendFormat": "{{ mountpoint}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(heritrix3_crawl_job_threads_total{job=\"npld-dc-heritrix-workers\"}[30m])) by (kind)",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(heritrix3_crawl_job_queues_total{job=\"npld-dc-heritrix-workers\"}) by (kind)",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "URL Totals Over 100 Days",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(heritrix3_crawl_job_uris_total{job=\"npld-dc-heritrix-workers\",kind!~\"discovered|queued\"}) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Bytes (Uncompressed, larger than WARC size)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(heritrix3_crawl_job_bytes_total{job=\"npld-dc-heritrix-workers\", kind!=\"warc-novel\"}) by (kind)",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "Network Data Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance='crawler08:9100',device=~'e.+'}[30m]) > 10",
     "legendFormat": "RX {{ device }}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance='crawler08:9100',device=~'e.+'}[5m]) > 10",
     "legendFormat": "TX {{ device }}"
    }
   ]
  },
  {
   "title": "Heritrix Alert Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "heritrix3_crawl_job_alerts_count{jobname=\"dc2020\"}",
     "legendFormat": "{{jobname}}"
    }
   ]
  }
 ]
}