{
 "title": "Disk Usage Stats",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Network Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~'en.*'}[20m])",
     "legendFormat": "RX {{ instance }} {{ device }}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~'en.*'}[20m])",
     "legendFormat": "TX {{ instance }} {{ device }}"
    },
    {
     "expr": "rate(node_network_receive_bytes{device=~'en.*'}[20m])",
     "legendFormat": "RX {{ instance }} {{ device }}"
    },
    {
     "expr": "rate(node_network_transmit_bytes{device=~'en.*'}[20m])",
     "legendFormat": "TX {{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100.0*node_filesystem_free{fstype=~\"ext2|ext4|xfs|fuse.glusterfs\",mountpoint!~\".*/docker/.*|/boot\"}/node_filesystem_size",
     "legendFormat": "{{ instance }} {{mountpoint}}"
    },
    {
     "expr": "100.0 - 100.0*node_filesystem_free_bytes{fstype=~\"ext2|ext4|xfs|fuse.glusterfs\",mountpoint!~\".*/docker/.*|/boot\"}/node_filesystem_size_bytes",
     "legendFormat": "{{ instance }} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk usage change per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "-delta(node_filesystem_free{fstype=~\"ext2|ext4|xfs|fuse.glusterfs\",mountpoint!~\".*/docker/.*|/boot\"}[1h])",
     "legendFormat": "{{ instance}}:{{mountpoint}}"
    },
    {
     "expr": "-delta(node_filesystem_free_bytes{fstype=~\"ext2|ext4|xfs|fuse.glusterfs\",mountpoint!~\".*/docker/.*|/boot\"}[1h])",
     "legendFormat": "{{ instance}}:{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent", "label": "CPU load %tage" }
   ],
   "targets": [
    {
     "expr": "100 - 100*avg(irate(node_cpu{mode='idle'}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "100 - 100*avg(irate(node_cpu_seconds_total{mode='idle'}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Load Average [15m]  / CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Load Average / CPU" }
   ],
   "targets": [
    {
     "expr": "avg(node_load15) BY (instance) /  count(node_cpu{mode='user'}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg(node_load15) BY (instance) /  count(node_cpu_seconds_total{mode='user'}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Percentage of time spent in IOwait state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    {
     "format": "short",
     "label": "% time CPU spent in iowait state"
    }
   ],
   "targets": [
    {
     "expr": "100*avg(irate(node_cpu{mode=\"iowait\"}[5m]))  by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100*avg(irate(node_cpu_seconds_total{mode=\"iowait\"}[5m]))  by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal) by (instance) - sum(node_memory_MemFree + node_memory_Buffers + node_memory_Cached) by (instance) ) / sum(node_memory_MemTotal) by (instance) * 100",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes) by (instance) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) by (instance) ) / sum(node_memory_MemTotal_bytes) by (instance) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}