{
 "title": "Domain Crawler Summary",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Kafka Message Processing Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_offset[10m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Kafka Stacked Sum of  Current Offsets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_offset) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Active Domain Crawl Heritrix Frontier Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(heritrix3_crawl_job_queues_total{deployment='domain', kind='total'}) - sum(heritrix3_crawl_job_queues_total{deployment='domain', kind='exhausted'})  - sum(heritrix3_crawl_job_queues_total{deployment='domain', kind='retired'})",
     "legendFormat": "queues neither exhausted nor retired"
    },
    {
     "expr": "sum(heritrix3_crawl_job_queues_total{deployment='domain', kind='snoozed'})",
     "legendFormat": "snoozed queues"
    }
   ]
  },
  {
   "title": "Domain Crawl Heritrix Frontier URIs Awaiting Crawl",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(heritrix3_crawl_job_uris_total{deployment='domain',kind='queued'}) - sum(heritrix3_crawl_job_uris_total{deployment='domain',kind='downloaded'})"
    }
   ]
  },
  {
   "title": "Domain Crawl Heritrix Frontier Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(heritrix3_crawl_job_queues_total{deployment='domain'}) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Domain Crawl Heritrix Toe Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(heritrix3_crawl_job_threads_total{deployment='domain',kind!='congestion-ratio'}) by (kind)",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "Domain Crawl URL Totals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(heritrix3_crawl_job_uris_total{deployment='domain'}) by (kind)",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "Rate of change of the total number of Heritrix Frontier  Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(heritrix3_crawl_job_queues_total{deployment='domain',kind='total'}[10m]))"
    }
   ]
  },
  {
   "title": "Domain Crawl Bytes Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(heritrix3_crawl_job_bytes_total{deployment='domain'}) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Domain Crawler Congestion Ratios",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "heritrix3_crawl_job_threads_total{deployment='domain',kind='congestion-ratio'}",
     "legendFormat": "{{ id }}"
    }
   ]
  }
 ]
}