{
 "title": "Hadoop HDFS FSImage",
 "description": "Used with Prometheus Hadoop HDFS FSImage Exporter",
 "tags": [
  "hdfs",
  "fsimage"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "user_name",
    "query": "label_values(fsimage_user_dirs,user_name)"
   },
   {
    "name": "group_name",
    "query": "label_values(fsimage_group_dirs,group_name)"
   },
   {
    "name": "instance",
    "query": "label_values(fsimage_group_dirs,instance)"
   }
  ]
 },
 "panels": [
  { "title": "FSImage global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "fsimage_dirs",
   "type": "graph",
   "description": "Number of directories.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(fsimage_dirs)" }
   ]
  },
  {
   "title": "fsimage_blocks",
   "type": "graph",
   "description": "Number of blocks.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(fsimage_blocks)" }
   ]
  },
  {
   "title": "fsimage_links",
   "type": "graph",
   "description": "Number of sym links.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(fsimage_links)" }
   ]
  },
  {
   "title": "fsimage_replication_sum",
   "type": "graph",
   "description": "Overall file replication",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(fsimage_replication_sum)" }
   ]
  },
  {
   "title": "fsimage_fsize_sum",
   "type": "graph",
   "description": "Overall file size distribution",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "max(fsimage_fsize_sum)" }
   ]
  },
  {
   "title": "fsimage_fsize_bucket",
   "type": "graph",
   "description": "Overall file size distribution",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fsimage_fsize_bucket" }
   ]
  },
  { "title": "User/Group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "fsimage_user_dirs",
   "type": "graph",
   "description": "Number of directories.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(fsimage_user_dirs{user_name=~\"$user_name\"})",
     "legendFormat": "$user_name"
    }
   ]
  },
  {
   "title": "fsimage_user_blocks",
   "type": "graph",
   "description": "Number of blocks.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(fsimage_user_blocks{user_name=~\"$user_name\"})",
     "legendFormat": "$user_name"
    }
   ]
  },
  {
   "title": "fsimage_user_links",
   "type": "graph",
   "description": "Number of sym links.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(fsimage_user_links{user_name=~\"$user_name\"})",
     "legendFormat": "$user_name"
    }
   ]
  },
  {
   "title": "fsimage_user_replication_sum",
   "type": "graph",
   "description": "Per user file replication",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(fsimage_user_replication_sum{user_name=~\"$user_name\"})",
     "legendFormat": "$user_name"
    }
   ]
  },
  {
   "title": "fsimage_user_fsize_bucket",
   "type": "graph",
   "description": "Overall file size distribution\nFIXME",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fsimage_user_fsize_bucket{user_name=~\"$user_name\"}"
    }
   ]
  },
  {
   "title": "fsimage_group_dirs",
   "type": "graph",
   "description": "Number of directories.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(fsimage_group_dirs{group_name=~\"$group_name\"})",
     "legendFormat": "$group_name"
    }
   ]
  },
  {
   "title": "fsimage_group_blocks",
   "type": "graph",
   "description": "Number of blocks.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(fsimage_group_blocks{group_name=~\"$group_name\"})",
     "legendFormat": "$group_name"
    }
   ]
  },
  {
   "title": "fsimage_group_links",
   "type": "graph",
   "description": "Number of sym links.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(fsimage_group_links{group_name=~\"$group_name\"})",
     "legendFormat": "$group_name"
    }
   ]
  },
  {
   "title": "fsimage_group_fsize_bucket",
   "type": "graph",
   "description": "Overall file size distribution\nFIXME",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fsimage_group_fsize_bucket{group_name=~\"$group_name\"}"
    }
   ]
  },
  { "title": "FSImage loading/parsing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "fsimage_load_duration_seconds_sum rate",
   "type": "graph",
   "description": "Time for loading/parsing FSImage.\n",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(fsimage_load_duration_seconds_sum{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "fsimage_compute_stats_duration_seconds_sum rate",
   "type": "graph",
   "description": "for computing stats for a loaded FSImage",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(fsimage_compute_stats_duration_seconds_sum{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "fsimage_load_file_size_bytes",
   "type": "graph",
   "description": "Size of raw FSImage",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "fsimage_load_file_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Scraping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "fsimage_scrape_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "fsimage_scrape_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "fsimage_scrape_requests_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fsimage_scrape_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "fsimage_scrape_errors_total rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fsimage_scrape_errors_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "fsimage_exporter_app_info",
   "type": "graph",
   "description": "TODO: do it as somethig different?\nIt always returns 1.0",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fsimage_exporter_app_info{instance=~\"$instance\"}",
     "legendFormat": "appVersion {{appVersion}}, instance {{instance}} "
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "jvm_memory_bytes_used",
   "type": "graph",
   "description": "Used bytes of a given JVM memory area.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$instance\"}",
     "legendFormat": "{{area}} {{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_bytes_committed",
   "type": "graph",
   "description": "Committed (bytes) of a given JVM memory area.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{instance=~\"$instance\"}",
     "legendFormat": "{{area}} {{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_bytes_max",
   "type": "graph",
   "description": "Max (bytes) of a given JVM memory area.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{instance=~\"$instance\"}",
     "legendFormat": "{{area}} {{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_bytes_init",
   "type": "graph",
   "description": "Initial bytes of a given JVM memory area.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_init{instance=~\"$instance\"}",
     "legendFormat": "{{area}} {{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_used",
   "type": "graph",
   "description": "Used bytes of a given JVM memory pool.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\"}",
     "legendFormat": "{{pool}} {{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_committed",
   "type": "graph",
   "description": "Committed bytes of a given JVM memory pool.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=~\"$instance\"}",
     "legendFormat": "{{pool}} {{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_max",
   "type": "graph",
   "description": "Max bytes of a given JVM memory pool.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{instance=~\"$instance\"}",
     "legendFormat": "{{pool}} {{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_init",
   "type": "graph",
   "description": "Initial bytes of a given JVM memory pool.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_init{instance=~\"$instance\"}",
     "legendFormat": "{{pool}} {{instance}}"
    }
   ]
  }
 ]
}