{
 "title": "Task Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Time Since Last Successful Run",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "expr": "(time() - ukwa_task_event_timestamp{job=~'DailyAccessTasks|DailyIngestTasks'}) / (60*60)",
     "legendFormat": "{{ job }} {{ status }}"
    }
   ]
  },
  {
   "title": "# Tasks Run v. Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(ukwa_task_status == 1)", "legendFormat": "# jobs run successfully" },
    {
     "expr": "count(ukwa_task_status == 0) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ukwa_task_status == 0) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}