{
 "title": "UKWA Metrics Tracking",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total NPLD Data on HDFS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(ukwa_files_total_bytes{collection='npld',kind='all',stream!=''})"
    }
   ]
  },
  {
   "title": "Target Records Processed, by Job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ukwa_record_count{kind='targets'}) by (job)",
     "legendFormat": "Target records"
    }
   ]
  },
  {
   "title": "Collection Records, by Job & Kind",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ukwa_record_count{kind='collections'}) by (job, status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "WARCs CDX Indexed & Verified",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ukwa_task_warcs_cdx_verified" }
   ]
  },
  {
   "title": "URL Counts, by Job & Kind",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ukwa_url_count) by (job,set)",
     "legendFormat": "{{job}}: {{set}}"
    }
   ]
  },
  {
   "title": "Total NPLD Data on HDFS, by Kind",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(ukwa_files_total_bytes{collection='npld',kind!='all',stream!=''}) by (kind)",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "Non-NPLD Data on HDFS, by Collection, Stream & Kind",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(ukwa_files_total_bytes{kind!='all',collection!=\"npld\"}) by (kind,stream,collection)",
     "legendFormat": "{{collection}}<br>{{ stream }}<br>{{ kind }}"
    }
   ]
  }
 ]
}