{
 "title": "WA Individual Server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "up{instance=~\".*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Servers Down",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(1 - up{instance=\"$server\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{fstype!~\"tmpfs|rootfs\",instance=\"$server\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|rootfs\",instance=\"$server\"}) * 100",
     "legendFormat": "{{ instance }} {{ mountpoint }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - 100*(irate(node_cpu_seconds_total{instance=\"$server\",mode='idle'}[5m]))",
     "legendFormat": "{{ $server }} - {{ cpu }}"
    }
   ]
  },
  {
   "title": "IO wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(irate(node_cpu_seconds_total{instance=\"$server\",mode=\"iowait\"}[5m])) * 100",
     "legendFormat": "{{ instance }} - {{ cpu }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"$server\"} - node_memory_MemFree_bytes{instance=\"$server\"} - node_memory_Buffers_bytes{instance=\"$server\"} - node_memory_Cached_bytes{instance=\"$server\"}) / node_memory_MemTotal_bytes{instance=\"$server\"}) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 } },
  {
   "title": "Network activity RX",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$server\",device=~\"e.+\"}[5m])",
     "legendFormat": "RX {{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "Network activity TX",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$server\",device=~\"e.+\"}[5m])",
     "legendFormat": "TX {{ instance }} {{ device }}"
    }
   ]
  }
 ]
}