{
 "title": "WA Job Servers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "up{instance=~\".*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Servers Down",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(1 - up{job=\"$job\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{fstype!~\"tmpfs|rootfs\",job=\"$job\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|rootfs\",job=\"$job\"}) * 100",
     "legendFormat": "{{ instance }} {{ mountpoint }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - 100*avg(irate(node_cpu_seconds_total{mode='idle',job=\"$job\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "IO wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*avg(irate(node_cpu_seconds_total{job=\"$job\",mode=\"iowait\"}[5m]))  by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"$job\"} - node_memory_MemFree_bytes{job=\"$job\"} - node_memory_Buffers_bytes{job=\"$job\"} - node_memory_Cached_bytes{job=\"$job\"}) / node_memory_MemTotal_bytes{job=\"$job\"}) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 } },
  {
   "title": "Network activity RX",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"$job\",device=~\"e.+\"}[5m])",
     "legendFormat": "RX {{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "Network activity TX",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"$job\",device=~\"e.+\"}[5m])",
     "legendFormat": "TX {{ instance }} {{ device }}"
    }
   ]
  }
 ]
}