{
 "title": "WA Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Ingest & Metadata", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1 - up{job=\"ingest_metadata\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(irate(node_cpu_seconds_total{job=\"ingest_metadata\",mode=\"idle\"}[5m]) < 0.1) by (instance)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Dsk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((node_filesystem_avail_bytes{job=\"ingest_metadata\",fstype!~\"tmpfs|rootfs|cifs\"} / node_filesystem_size_bytes{job=\"ingest_metadata\",fstype!~\"tmpfs|rootfs|cifs\"}) < 0.04) OR vector(0)"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(node_memory_MemFree_bytes{job=\"ingest_metadata\"} + node_memory_Buffers_bytes{job=\"ingest_metadata\"} + node_memory_Cached_bytes{job=\"ingest_metadata\"}) by (instance) / sum(node_memory_MemTotal_bytes{job=\"ingest_metadata\"}) by (instance) < 0.05) OR vector(0)"
    }
   ]
  },
  {
   "title": "WWW",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"im-access-http\"} != 200) OR vector(0)"
    }
   ]
  },
  { "title": "Hadoop", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 8, "y": 0 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1 - up{job=\"hadoop\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(irate(node_cpu_seconds_total{job=\"hadoop\",mode=\"idle\"}[5m]) < 0.1) by (instance)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hdfs_node_count{status=\"dead\",instance=\"hdfs-exporter.dapi.wa.bl.uk:80\"}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hdfs_used_percent{instance=\"hdfs-exporter.dapi.wa.bl.uk:80\"}"
    }
   ]
  },
  {
   "title": "Dsk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((node_filesystem_avail_bytes{job=\"hadoop\",fstype!~\"tmpfs|rootfs|cifs\"} / node_filesystem_size_bytes{job=\"hadoop\",fstype!~\"tmpfs|rootfs|cifs\"}) < 0.04) OR vector(0)"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(node_memory_MemFree_bytes{job=\"hadoop\"} + node_memory_Buffers_bytes{job=\"hadoop\"} + node_memory_Cached_bytes{job=\"hadoop\"}) by (instance) / sum(node_memory_MemTotal_bytes{job=\"hadoop\"}) by (instance) < 0.05) OR vector(0)"
    }
   ]
  },
  {
   "title": "Under-rep",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hdfs_under_replicated_block_count{instance=\"hdfs-exporter.dapi.wa.bl.uk:80\"}"
    }
   ]
  },
  { "title": "Discovery & Access", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1 - up{job=\"discovery_access\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(irate(node_cpu_seconds_total{job=\"discovery_access\",mode=\"idle\"}[5m]) < 0.1) by (instance)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Dsk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((node_filesystem_avail_bytes{job=\"discovery_access\",fstype!~\"tmpfs|rootfs|cifs\"} / node_filesystem_size_bytes{job=\"discovery_access\",fstype!~\"tmpfs|rootfs|cifs\"}) < 0.04) OR vector(0)"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(node_memory_MemFree_bytes{job=\"discovery_access\"} + node_memory_Buffers_bytes{job=\"discovery_access\"} + node_memory_Cached_bytes{job=\"discovery_access\"}) by (instance) / sum(node_memory_MemTotal_bytes{job=\"discovery_access\"}) by (instance) < 0.05) OR vector(0)"
    }
   ]
  },
  {
   "title": "UTR",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(uptimerobot_monitor_up==0) OR vector(0)"
    }
   ]
  },
  {
   "title": "WWW",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"da-access-http\"} != 200) OR vector(0)"
    }
   ]
  },
  { "title": "Services", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 5 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1 - up{job=\"services\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(irate(node_cpu_seconds_total{job=\"services\",mode=\"idle\"}[5m]) < 0.1) by (instance)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Dsk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((node_filesystem_avail_bytes{job=\"services\",fstype!~\"tmpfs|rootfs|cifs\"} / node_filesystem_size_bytes{job=\"services\",fstype!~\"tmpfs|rootfs|cifs\"}) < 0.04) OR vector(0)"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(node_memory_MemFree_bytes{job=\"services\"} + node_memory_Buffers_bytes{job=\"services\"} + node_memory_Cached_bytes{job=\"services\"}) by (instance) / sum(node_memory_MemTotal_bytes{job=\"services\"}) by (instance) < 0.05) OR vector(0)"
    }
   ]
  },
  { "title": "Gluster", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 8, "y": 6 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1 - up{job=\"gluster\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(irate(node_cpu_seconds_total{job=\"gluster\",mode=\"idle\"}[5m]) < 0.1) by (instance)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Dsk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((node_filesystem_avail_bytes{job=\"gluster\",fstype!~\"tmpfs|rootfs|cifs\"} / node_filesystem_size_bytes{job=\"gluster\",fstype!~\"tmpfs|rootfs|cifs\"}) < 0.04) OR vector(0)"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(node_memory_MemFree_bytes{job=\"gluster\"} + node_memory_Buffers_bytes{job=\"gluster\"} + node_memory_Cached_bytes{job=\"gluster\"}) by (instance) / sum(node_memory_MemTotal_bytes{job=\"gluster\"}) by (instance) < 0.05) OR vector(0)"
    }
   ]
  },
  { "title": "Solr", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 5 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1 - up{job=\"solr\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(irate(node_cpu_seconds_total{job=\"solr\",mode=\"idle\"}[5m]) < 0.1) by (instance)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Dsk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((node_filesystem_avail_bytes{job=\"solr\",fstype!~\"tmpfs|rootfs|cifs\"} / node_filesystem_size_bytes{job=\"solr\",fstype!~\"tmpfs|rootfs|cifs\"}) < 0.04) OR vector(0)"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(node_memory_MemFree_bytes{job=\"solr\"} + node_memory_Buffers_bytes{job=\"solr\"} + node_memory_Cached_bytes{job=\"solr\"}) by (instance) / sum(node_memory_MemTotal_bytes{job=\"solr\"}) by (instance) < 0.05) OR vector(0)"
    }
   ]
  },
  {
   "title": "Query",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"solr-query\"} != 200) OR vector(0)"
    }
   ]
  },
  { "title": "Infrastructure", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 8, "y": 9 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1 - up{job=\"infrastructure\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(irate(node_cpu_seconds_total{job=\"infrastructure\",mode=\"idle\"}[5m]) < 0.1) by (instance)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Dsk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((node_filesystem_avail_bytes{job=\"infrastructure\",fstype!~\"tmpfs|rootfs|cifs\"} / node_filesystem_size_bytes{job=\"infrastructure\",fstype!~\"tmpfs|rootfs|cifs\"}) < 0.04) OR vector(0)"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(node_memory_MemFree_bytes{job=\"infrastructure\"} + node_memory_Buffers_bytes{job=\"infrastructure\"} + node_memory_Cached_bytes{job=\"infrastructure\"}) by (instance) / sum(node_memory_MemTotal_bytes{job=\"infrastructure\"}) by (instance) < 0.05) OR vector(0)"
    }
   ]
  },
  { "title": "WA Services", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "trackdb refresh",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - trackdb_refresh_timestamp{job=\"trackdb\"}) / (60*60)"
    }
   ]
  },
  {
   "title": "trackdb numFound",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trackdb_numFound{job=\"trackdb\"} - (trackdb_numFound{job=\"trackdb\"} offset 1d))"
    }
   ]
  }
 ]
}