{
 "title": "Solr",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "wa-www nginx status codes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "q/m" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_request_status{job=\"solr\",code=~\"2..\"}[2m]) * 60",
     "legendFormat": "{{ instance }} 200"
    },
    {
     "expr": "rate(nginx_request_status{job=\"solr\",code=~\"3..\"}[2m]) * 60",
     "legendFormat": "{{ instance }} 300"
    },
    {
     "expr": "rate(nginx_request_status{job=\"solr\",code=~\"4..\"}[2m]) * 60",
     "legendFormat": "{{ instance }} 400"
    },
    {
     "expr": "rate(nginx_request_status{job=\"solr\",code=~\"5..\"}[2m]) * 60",
     "legendFormat": "{{ instance }} 500"
    }
   ]
  },
  {
   "title": "solr-proxy httpd status codes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "q/m" }
   ],
   "targets": [
    {
     "expr": "rate(httpd_request_status{job=\"solr\",code=~\"2..\"}[2m]) * 60",
     "legendFormat": "{{ instance }} 200"
    },
    {
     "expr": "rate(httpd_request_status{job=\"solr\",code=~\"3..\"}[2m]) * 60",
     "legendFormat": "{{ instance }} 300"
    },
    {
     "expr": "rate(httpd_request_status{job=\"solr\",code=~\"4..\"}[2m]) * 60",
     "legendFormat": "{{ instance }} 400"
    },
    {
     "expr": "rate(httpd_request_status{job=\"solr\",code=~\"5..\"}[2m]) * 60",
     "legendFormat": "{{ instance }} 500"
    }
   ]
  },
  {
   "title": "Search qtime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    { "expr": "rate(qtime[2m])", "legendFormat": "{{ instance }}" }
   ]
  }
 ]
}