groups:
- name: FC metrics
  rules:
  - alert: low_crawler_activity
    # The NPLD crawler is busier:
    expr: increase(heritrix3_crawl_job_uris_total{kind="finished", jobname!="frequent-bypm"}[4h]) < 10
    for: 10m
    labels:
      severity: severe
    annotations:
      description: Low crawl rate for crawl job {{ $labels.jobname }}.
      summary: The {{ $labels.jobname }} crawl job is crawling too slowly.

  - alert: low_crawler_activity_bypm
    # By permissions crawls are not running all day, but every day:
    expr: increase(heritrix3_crawl_job_uris_total{kind="finished",jobname="frequent-bypm"}[24h]) == 0
    for: 10m
    labels:
      severity: severe
    annotations:
      description: Low crawl rate for crawl job {{ $labels.jobname }}.
      summary: The {{ $labels.jobname }} crawl job is crawling too slowly.
      
  - alert: fc_crawl_is_slow
    expr: sum(rate(kafka_log_logendoffset{topic="fc.crawled"}[10m])) < 5
    for: 30m
    labels:
      severity: severe
    annotations:
      summary: "The frequent crawls are not running as fast as expected!"
      description: "The frequent crawls do not appear to be running as fast as it should be."


#- name: DC metrics
#  rules:
#  - alert: low_dc_crawler_activity
#    expr: increase(heritrix3_crawl_job_uris_total{kind="finished", jobname="dc2024"}[4h]) < 10
#    for: 10m
#    labels:
#      severity: severe
#    annotations:
#      description: Low crawl rate for crawl job {{ $labels.jobname }}.
#      summary: The {{ $labels.jobname }} crawl job is crawling too slowly.
#     
#  - alert: dc_crawl_is_slow
#    expr: sum(rate(kafka_log_logendoffset{topic="dc.crawled"}[10m])) < 5
#    for: 30m
#    labels:
#      severity: severe
#    annotations:
#      summary: "The domain crawl is not running as fast as expected!"
#      description: "The domain crawl does not appear to be running as fast as it should be."


- name: Generic metrics
  rules:

  # Alert for any instance that is unreachable for >5 minutes.
  - alert: service_down
    expr: up == 0
    for: 2m
    labels:
      severity: severe
    annotations:
      summary: "Service {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  - alert: host_cpu_rate
    expr: 100 - 100*avg(irate(node_cpu_seconds_total{mode='idle'}[10m])) > 90
    for: 15m
    labels:
      severity: severe
    annotations:
      summary: "CPU rate on {{ $labels.instance }} > 90%"
      description: "CPU rate on {{ $labels.instance }} > 90% for more than 15 minutes"

  - alert: host_free_disk_space
    expr: (node_filesystem_avail_bytes{fstype=~"ext.|xfs"}/node_filesystem_size_bytes{fstype=~"ext.|xfs"}) * 100 < 15
    for: 5m
    labels:
      severity: severe
    annotations:
      summary: "Disk space free < 15% on {{ $labels.instance }}"
      description: "Disk space free on {{ $labels.instance }} has been less that 15% for more than 5 minutes"
