version: '3.2'
# prometheus monitoring service

services:
  alertmanager:
    image: prom/alertmanager:main
    ports:
      - "${ALERTMANAGER_PORT}:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager
      - "${ALERTMANAGER_DATA}:/alertmanager"
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://${ALERTMANAGER_SERVICE_NAME}/'

  prometheus:
    image: prom/prometheus:main
    ports:
      - "${PROMETHEUS_PORT}:9090"
    depends_on:
      - alertmanager
    user: root
    volumes:
      - ./prometheus:/etc/prometheus
      - "${PROMETHEUS_DATA}:/prometheus"
    extra_hosts:
      - 'fc:172.31.43.254'
      - "monitor:${SERVER_IP}"
      - 'ac:172.31.20.115'
      - 'dc:172.31.25.96'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=180d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=http://${PROMETHEUS_SERVICE_NAME}/'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:main
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus
    user: "1000"
    extra_hosts:
      - 'fc:172.31.43.254'
      - "monitor:${SERVER_IP}"
      - 'dc:172.31.25.96'
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_NAME=${GRAFANA_ORG_NAME}"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer"
      - "GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}"
    volumes:
      - ./grafana:/etc/grafana
      - "${GRAFANA_DATA}:/var/lib/grafana"
