{
 "title": "WA Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "WA server status timeline",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - 100*avg(irate(node_cpu_seconds_total{mode='idle'}[5m])) by (instance)"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{fstype!~\"tmpfs\"} / node_filesystem_size_bytes{fstype!~\"tmpfs\"}) * 100"
    },
    {
     "expr": "(node_memory_Active_bytes / on (instance) node_memory_MemTotal_bytes) * 100"
    },
    {
     "expr": "100*avg(irate(node_cpu_seconds_total{mode=\"iowait\"}[5m]))  by (instance)"
    }
   ]
  },
  { "title": "Ingest & Metadata", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 6 } },
  { "title": "Hadoop", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 8, "y": 6 } },
  { "title": "Discovery & Access", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 6 } },
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(1 - up{job=\"ingest_metadata\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 2, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(irate(node_cpu_seconds_total{job=\"ingest_metadata\",mode='idle'}[5m]) < 0.1) by (instance)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((node_filesystem_avail_bytes{job=\"ingest_metadata\",fstype!~\"cifs|tmpfs\"} / node_filesystem_size_bytes{job=\"ingest_metadata\",fstype!~\"cifs|tmpfs\"}) < 0.04) OR vector(0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((node_memory_MemFree_bytes{job=\"ingest_metadata\"} / node_memory_MemTotal_bytes{job=\"ingest_metadata\"}) < 0.01) OR vector(0)"
    }
   ]
  },
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(1 - up{job=\"hadoop\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 10, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(irate(node_cpu_seconds_total{job=\"hadoop\",mode='idle'}[5m]) < 0.1) by (instance)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((node_filesystem_avail_bytes{job=\"hadoop\",fstype!~\"cifs|tmpfs\"} / node_filesystem_size_bytes{job=\"hadoop\",fstype!~\"cifs|tmpfs\"}) < 0.04) OR vector(0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 14, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((node_memory_MemFree_bytes{job=\"hadoop\"} / node_memory_MemTotal_bytes{job=\"hadoop\"}) < 0.01) OR vector(0)"
    }
   ]
  },
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(1 - up{job=\"discovery_access\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(irate(node_cpu_seconds_total{job=\"discovery_access\",mode='idle'}[5m]) < 0.1) by (instance)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((node_filesystem_avail_bytes{job=\"discovery_access\",fstype!~\"cifs|tmpfs\"} / node_filesystem_size_bytes{job=\"discovery_access\",fstype!~\"cifs|tmpfs\"}) < 0.04) OR vector(0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 22, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((node_memory_MemFree_bytes{job=\"discovery_access\"} / node_memory_MemTotal_bytes{job=\"discovery_access\"}) < 0.01) OR vector(0)"
    }
   ]
  },
  { "title": "Gluster", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 8, "y": 8 } },
  { "title": "Solr", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 8 } },
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(1 - up{job=\"gluster\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 10, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(irate(node_cpu_seconds_total{job=\"gluster\",mode='idle'}[5m]) < 0.1) by (instance)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((node_filesystem_avail_bytes{job=\"gluster\",fstype!~\"cifs|tmpfs\"} / node_filesystem_size_bytes{job=\"gluster\",fstype!~\"cifs|tmpfs\"}) < 0.04) OR vector(0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 14, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((node_memory_MemFree_bytes{job=\"gluster\"} / node_memory_MemTotal_bytes{job=\"gluster\"}) < 0.01) OR vector(0)"
    }
   ]
  },
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(1 - up{job=\"solr\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(irate(node_cpu_seconds_total{job=\"solr\",mode='idle'}[5m]) < 0.1) by (instance)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((node_filesystem_avail_bytes{job=\"solr\",fstype!~\"cifs|tmpfs\"} / node_filesystem_size_bytes{job=\"solr\",fstype!~\"cifs|tmpfs\"}) < 0.04) OR vector(0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 22, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((node_memory_MemFree_bytes{job=\"solr\"} / node_memory_MemTotal_bytes{job=\"solr\"}) < 0.1) OR vector(0)"
    }
   ]
  },
  { "title": "Infrastructure", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 8, "y": 10 } },
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(1 - up{job=\"infrastructure\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 10, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(irate(node_cpu_seconds_total{job=\"infrastructure\",mode='idle'}[5m]) < 0.1) by (instance)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((node_filesystem_avail_bytes{job=\"infrastructure\",fstype!~\"cifs|tmpfs\"} / node_filesystem_size_bytes{job=\"infrastructure\",fstype!~\"cifs|tmpfs\"}) < 0.04) OR vector(0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 2, "x": 14, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((node_memory_MemFree_bytes{job=\"infrastructure\"} / node_memory_MemTotal_bytes{job=\"infrastructure\"}) < 0.01) OR vector(0)"
    }
   ]
  }
 ]
}